### ISSUE TITLE
Configure Opengrok to not have source in the URL path

### ISSUE THREAD

**Issue by lekanovic** [OpenGrok/OpenGrok#1038]
I would like to know if it's possible to configure so that the "/source" is not part of the URL

```
From:
http://<YOUR_WEBAPP_SERVER>:<WEBAPPSRV_PORT>/source
To:
http://<YOUR_WEBAPP_SERVER>:<WEBAPPSRV_PORT>/
```

Thanks!

**Comment by tarzanek** [comment]
Use this env option before index: OPENGROK_WEBAPP_CONTEXT  
docs:
https://github.com/OpenGrok/OpenGrok/blob/master/OpenGrok#L60
and then rename source.war to whatever needed
in case of just "" you would just explode the .war to root
I am however wondering if above variable can be "" 
care to test and let me know ?

tia
L

**Comment by dhireng** [comment]
can you not just have a simple redirect HTML in ROOT

**Comment by tarzanek** [comment]
@dhireng 
feel free to open a pull request
fwiw - I tried to do some research and it would work with it, just some paths would be very ../../../../../../..
populated
so index size would increase (a lot) ... that's why I never didn't try to fix this ... (obviously for shalow repos it wouldn't matter and perhaps would save disk space, but for e.g. java classes the xrefs would go up size wise A LOT)
so it's about a trade off - space Vs how easy is to change /source to something else
and back then I think @chandanbn sacrificed fixed webapp name to keep the xref size down (this is what I think based on my research, it might have changed in between, I am not sure if html5 can help here)

**Comment by Jaysonsu** [comment]
@tarzanek，
We try to rename source.war to xxx.war,the basic redirect is ok,but when we want to click method or class from files(e.g.http://10.92.35.11:8080/xxx/xref/packages/apps/Bluetooth/src/com/android/bluetooth/a2dp/A2dpSinkStateMachine.java),it will redirect to source (http://10.92.35.11:8080/source/s?refs=A2dpSinkStateMachine&project=packages).I find that opengrok source code some analyse file has fixed as 'source/s?'.
What should I do?We have more than one project to run.

**Comment by tarzanek** [comment]
@Jaysonsu you don't use the proper option when indexing ... OPENGROK_WEBAPP_CONTEXT
OPENGROK_WEBAPP_CONTEXT="xxx" OpenGrok index ....
see https://github.com/OpenGrok/OpenGrok/blob/master/OpenGrok#L60

**Comment by Jaysonsu** [comment]
It's OK now.Thanks!

**Comment by 5cmpersec** [comment]
@tarzanek 
Sorry, I am getting a similar issue with openGrok indexing in multiple projects, although OPENGROK_WEBAPP_CONTEXT is set properly, but some "search" links are still not correct.

My configs: lwip.conf

> OPENGROK_INSTANCE_BASE=/media/DISK2/opengrok/lwip
> OPENGROK_WEBAPP_CONTEX=lwip
> OPENGROK_VERBOSE=yes
> OPENGROK_PROGRESS=yes
> IGNORE_PATTERNS="-i *.jar -i *.so -i *.so -d:out -i d:.git"

My command to index:
`$ sudo OPENGROK_CONFIGURATION=./lwip.conf OPENGROK_WEBAPP_CONTEXT=lwip /bin/OpenGrok index`

Almost direct links to a specific file are OK, however, **search** items are not correct
Good links: http://localhost:8080/lwip/xref/lwip/src/core/udp.c
Bad search links: http://localhost:8080/**source**/s?defs=LWIP_UDP&project=lwip

I think there may be some errors in web function request.getContextPath() ? It may return default value in some ways ?
I already added META-INF/context.xml, but no luck :(

Do anybody know this issue ?

**Comment by kahatlen** [comment]
@5cmpersec, did you delete the /media/DISK2/opengrok/lwip/data directory before you ran the indexer with the OPENGROK_WEBAPP_CONTEXT option? The indexer generates some html fragments that have the context path hard-coded, so they need to be regenerated if the context path is changed.

**Comment by 5cmpersec** [comment]
@kahatlen Thank you very much! It's working now.

**Comment by 5cmpersec** [comment]
@kahatlen This issue occurs again today. I confirm that "data" & "etc" directory is deleted and OPENGROK_WEBAPP_CONTEXT is set properly. It is very strange that "source" is always added in search URL.
> http://phnl-git:8080/**source**/s?refs=SECDIR&project=system

**Comment by 5cmpersec** [comment]
@tarzanek, @kahatlen 
Sorry.
This issue is very strange now.
The "search" links (same object) display different among browsers (Chromium, Google Chrome, and FireFox).

This is the page's source:
`Chromium: <a href="/**source**/s?path=lwip/udp.h">udp.h</a>` ==> Wrong!
`Google Chrome: <a href="/**lwip**/s?path=lwip/udp.h">udp.h</a>` ==> Right!

If the ContextPath is hard-coded in the /data/ folder, How could it happens ?
Thank you for your help!

**Comment by tarzanek** [comment]
yes, Ctrl+Shift+R
or Ctrl+Shift+F5

the cache is preserved in browser, we should review caching, since it seems it might be wrong for some corner cases

**Comment by tarzanek** [comment]
@wrporter use OPENGROK_WEBAPP_CONTEXT and it will then have to be "/" I guess
never tried it though, can you test that approach? ev. document what the context would be ?

**Comment by wrporter** [comment]
Running this in a docker container on alpine. Using Tomcat as my app server. By doing the following, I get the UI at the root context. I decided not to modify the `OpenGrok` script, since it has `source.war` hardcoded. Not sure what this would look like on other app servers though.

```
ENV OPENGROK_WEBAPP_CONTEXT ""
RUN rm -rf $OPENGROK_TOMCAT_BASE/webapps/*
RUN cp -p $OPENGROK_INSTANCE_BASE/lib/source.war $OPENGROK_TOMCAT_BASE/webapps/ROOT.war
```

**Comment by tarzanek** [comment]
@wrporter cool, co just empty works, I hope xrefs get generated too
yes, the rename inside of OpenGrok might not be ready for empty webapp context - do you mind filing an issue for that please? So we can track this and ev. fix in future.
tia
L

**Comment by tulinkry** [comment]
#431

**Comment by wrporter** [comment]
@tarzanek xrefs appear to be generated properly. I haven't had any issues yet.

**Comment by catesandrew** [comment]
Using `v1.1-rc3` and the xrefs get generated but when looking at a file, Annotate, Line#, Scopes#, and Navigate# no longer work. I am using git and have tried both empty "" and "/" for the `OPENGROK_WEBAPP_CONTEXT`.

If you have something you want me to try I'll do it. I'm already unzipping the ROOT.war into ROOT so I can modify `localhost:2424` to point the machine name, `opengrok`, since my cron job runs in another container, `opengrok-cron`, inherited from `opengrok`. The cron container runs index and then sends that to `opengrok:2424`. The cron also syncs the git repos into the src directories, etc.

Running opengrok from the `tomcat:8-alpine` docker image has me in at around 300MB including building universal-ctags. Runs wicked fast as advertised.

**Comment by idodeclare** [comment]
@catesandrew , this has been fully supported since 1.1-rc27 by rewriting of xrefs based on `getContextPath()`.
