### ISSUE TITLE
Group config disappears from configuration.xml

### ISSUE THREAD

**Issue by kosi2801** [OpenGrok/OpenGrok#1065]
Running master as of Feb 23rd.
I added a configuration for project groups to my configuration.xml and upon ./OpenGrok update and Tomcat restart the groups are visible on the start page as expected.

But the configuration of the groups was removed from configuration.xml so I'm not sure if the current grouping state will persist if I do another ./OpenGrok update.

Am I missing something here which I should have done or is there possibly a bug?

I followed the configuration example from #1029.

**Comment by tulinkry** [comment]
This is not supported yet. A way to use groups persistently is to always provide a read-only configuration which you can do by either
 - providing READ_XML_CONFIGURATION variable [OpenGrok#L74](https://github.com/OpenGrok/OpenGrok/blob/master/OpenGrok#L74) to your run like
```READ_XML_CONFIGURATION=/some/path/to/xml ./Opengrok update```
 - or when using java startup with switch -R /path/to/xml/configuration       
```java -jar opengrok.jar <other parameters> -R /path/to/xml/configuration```

In that xml you should provide the group configuration (like example #1029) (or/and other values you want to change in your final configuration.xml - this read-only configuration gets merged with the other values).

I see that this is not really intuitive and the whole feature is not fully documented (yet). I will fix this into master asap.

**Comment by kosi2801** [comment]
Thanks for the hint. This workaround works for me for the time being.
When you fix this, will the behavior of the configuration.xml-generation be fixed or just the documentation of the workaround?

**Comment by tulinkry** [comment]
I meant the persistent group state (in configuration.xml-generation).

**Comment by tulinkry** [comment]
OK. I digged a bit in a code and it's not a trivial change and also it's against the original design (configuration is generated when the indexer runs, sent through socket to webapp). I wouldn't call the a workaround because it was mainly designed that way.
The option described above:

 - providing READ_XML_CONFIGURATION variable [OpenGrok#L74](https://github.com/OpenGrok/OpenGrok/blob/master/OpenGrok#L74) to your run like
```READ_XML_CONFIGURATION=/some/path/to/xml ./Opengrok update```
 - or when using java startup with switch -R /path/to/xml/configuration       
```java -jar opengrok.jar <other parameters> -R /path/to/xml/configuration```

is the only way to provide persistent group state. 

Possible friendliness is to export READ_XML_CONFIGURATION in shell environment used for grok indexing, or exporting it in ~/.bashrc (or other file which is loaded when shell starts) so it's available when grok starts indexing.
Moreover you can put your read only configuration into /var/opengrok/etc/groups.xml and set the environment variable to point to that file. Then you have both configurations on the same place.

**Comment by vladak** [comment]
Or use `OPENGROK_CONFIGURATION` environment variable which points to shell script if using the `OpenGrok` shell script and store all the config values from that script, e.g.:

```
$ cat /var/opengrok/etc/config
EXUBERANT_CTAGS=/usr/local/bin/ctags
READ_XML_CONFIGURATION=/var/opengrok/etc/readonly_config.xml
$ OPENGROK_CONFIGURATION=/var/opengrok/etc/config /usr/opengrok/bin/OpenGrok index
```
