### ISSUE TITLE
Bad End of Line appears in HTML for C and C++ index files

### ISSUE THREAD

**Issue by JosephHenry** [OpenGrok/OpenGrok#1163]
Starting at or around 0.13RC2 C and C++ files that were indexed have an End Of Line appear in the HTML file whenever a "//" is present.

I have attached an image to better visualize the problem.

This only happens with comments of type //

![grokproblem](https://cloud.githubusercontent.com/assets/21060229/17700193/b97590bc-6392-11e6-8ad3-15a2e3d9140d.jpg)

**Comment by tarzanek** [comment]
based on @tulinkry investigation it seems
https://github.com/OpenGrok/OpenGrok/commit/056576c8479cda9cf2594e5bb6cbb127ebc16b17#diff-f5d483b77907916b55ae4ab36ed48e03
from @kahatlen is the root cause
namely line #122 - if out.write gets commented out on https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/c/CXref.lex#L122 the xrefs will look OK again ...
@kahatlen I think we will need your expertise here ...
