### ISSUE TITLE
Main Search UI project selector is Buggy

### ISSUE THREAD

**Issue by JosephHenry** [OpenGrok/OpenGrok#1295]
I just upgrade to 0.13-RC4 and the project selector has changed.

The first issue, is that it looks really bad.  I am not sure if the project selector was supposed to change to check boxes, but if it was, the check boxes are above the project name, which is quite ugly.

The old project selector is still visible, but does not work in conjunction with the check boxes.

I have attached an image:

![image](https://cloud.githubusercontent.com/assets/21060229/20718370/7ec0f772-b626-11e6-9c1d-0ec485bc5ca2.png)

**Comment by tulinkry** [comment]
Browser? Any kind of errors in the browser console?

**Comment by vladak** [comment]
Marking as potential stopper.

**Comment by tulinkry** [comment]
There is not enough information to solve this. You can disable the project picker and use the old one as described in #1255.

**Comment by mrashmiranjan** [comment]
I also faced similar issue when I upgraded my opengrok from 0.12.x to 0.13-RC5. It turned out to be a browser caching issue. Browser had cached the css and js files from older version which probably was causing the new project selector look weird. Clearing the browser cache and/or refreshing the page pulled down the new files and the new look was back.

**Comment by tarzanek** [comment]
Ctrl+Shift+r
in browser as workaround?

**Comment by tulinkry** [comment]
No reaction. Seems to be solved by clearing the browser's cache.
Feel free to reopen if the problem persists.
