### ISSUE TITLE
Incorrect links in HTML when application is not deployed at /source

### ISSUE THREAD

**Issue by DaveRandom** [OpenGrok/OpenGrok#1424]
Probably I have done something wrong and/or there is a setting that I have missed here, but if so I cannot find it.

I have OpenGrok 0.13-rc9 deployed as ROOT.war in tomcat. Everything seems to work fine except that links on symbols in source files which point to a search page are still based on /source.

Is this hard-coded somewhere, or (more likely) have a I made a mistake somewhere along the line?

Concrete example: https://lxr.room11.org/xref/php-src%407.1/ext/standard/basic_functions.c#4537 - you can see the issue in the href of links that result in a search (rather than a jump-to-def).

    php_req.tv_sec = (time_t) tv_sec;

`php_req` => `/source/s?defs=php_req&project=php-src@7.1`
`tv_sec` => `/xref/php-src%407.1/ext/standard/basic_functions.c#tv_sec`
`time_t` => `/source/s?defs=time_t&project=php-src@7.1`
`tv_sec` => `/xref/php-src%407.1/ext/standard/basic_functions.c#tv_sec`

I would expect the `/source/s`-based links to point to `/s`, and indeed if you manually navigate to this URL then it works as expected.

Note that I have mitigated errors caused by the issue for now with an additional routing rule in the reverse proxy running in front of tomcat. Without that rule it was resulting in 404s.

**Comment by tulinkry** [comment]
This webapp context needs to be set during indexing because based on that the indexer generates the xrefs. 

1. If you use the `OpenGrok` wrapper then it is [`OPENGROK_WEBAPP_CONTEXT`](https://github.com/OpenGrok/OpenGrok/blob/master/OpenGrok#L62) env variable.
2. If you use grok jar file then it is:
```text
-w webapp-context
	Context of webapp. Default is /source. If you specify a different name, make sure to rename source.war to that name. Also FULL reindex is needed if this is changed.
```

**It's not enough to just rename the `.war` file.

The xrefs are working because that's a relative link to some token on the same page (`href="#tv_sec"` etc). It doesn't work for the undefined tokens as it generates the link to search for them elsewhere.

**Comment by tulinkry** [comment]
This could be related issues with some more information:
#1038 and #1105

**Comment by DaveRandom** [comment]
Great, I assumed it would be a mistake on my part, that answers my question, closing

Thanks a lot

**Comment by tulinkry** [comment]
You're welcome
