### ISSUE TITLE
add new message to trigger authorization plugin reload

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1569]
Currently the only way how to reload plugin configuration is to set new configuration. This can take long time due to `invalidateRepositories()` being called. New message directed just to reload auth plugin config would be nice to have, maybe with a possibility to specify concrete plugin type to be reloaded.

**Comment by tulinkry** [comment]
started thinking about this

> maybe with a possibility to specify concrete plugin type to be reloaded.

and I'm not sure if this is really a gain because our plugins use session to store some metadata and reloading the plugin will not necessarily invalidate the session; so this would mean to increase the plugin generation for all of the plugins - which eventually leads to that all plugins revalidate their session however this is not a single plugin reload

**Comment by vladak** [comment]
Okay, ditch the per-plugin idea.

**Comment by vladak** [comment]
Given the authorization framework refresh Message was implemented in c36f8e6106d16c5440e24746977aa2beec3c8f8b I think this one can be closed.
