### ISSUE TITLE
Why opengrok web instance running on tomcat has to collect all repositories data again

### ISSUE THREAD

**Issue by mmmarq** [OpenGrok/OpenGrok#1584]
Hi all,

I just realize that, after finish a huge repo base index (around 14k gits) and send new configuration file to tomcat, it (tomcat) just start to re-scan (collecting branch and history) all repositories info again. Is it really necessary??? I'm asking because tomcat stop to reply until all repositories info finishes and it takes to long. Also, I though this info was already embedded on XML file. Is there any way to disable it?

**Comment by vladak** [comment]
I think that's caused by `invalidateRepositories()` from `setConfiguration()` that goes through all the repositories and generally invokes relevant SCM command to see if it's indeed a repository. Since cset b2324f46 (Which version are you running by the way ?)  this is happening in parallel so that's not as bad as it used to be however thousands of repositories as is your case will make it still long.

**Comment by vladak** [comment]
To me the use case is valid (basically performing extended validation of configuration sent to the webapp that could really contain anything) however it should not cause the webapp to stop. So marking as a bug. Ideally, the validation should be performed in the background.

**Comment by mmmarq** [comment]
Hi Vladmir, you right, I did something wrong that kills my tomcat. I ran same tests today and webapp still responsive even while checking repo integrity. BTW, I'm running version 1.0
