### ISSUE TITLE
Error while running junit tests

### ISSUE THREAD

**Issue by ParmeetSingh** [OpenGrok/OpenGrok#1619]
Hi,

I am running the OpenGrok's test suite using the ant command.
ant -lib ./lib test

I am getting the following error.

create-razor-repository:

BUILD FAILED
/home/#######/OpenGrok-0.13-rc5/build.xml:706: The following error occurred while executing this line:
/home/#######/OpenGrok-0.13-rc5/build.xml:800: /home/#######/OpenGrok-0.13-rc5/ext/SampleRazorRepository/UserSandbox does not exist.

I am using
OpenGrok version: OpenGrok-0.13-rc5
Apache-Ant-1.9.0
JDK=1.8
Junit: 4.11
Ctags: ctags-5.8

**Comment by vladak** [comment]
Firstly, can you try with the fresh checked out current repository ?

The relevant pieces of `build.xml` looks like this:

```
115     <property name="test.razor" value="${test.repositories}/razor"/>
...
883     <target name="-create-razor-repository">
884         <delete dir="${test.razor}"/>
885         <copy todir="${test.razor}/Razor-Simple">
886             <fileset dir="ext/SampleRazorRepository/UserSandbox"/>
887         </copy>
```

I dowloaded https://github.com/OpenGrok/OpenGrok/archive/0.13-rc5.tar.gz, extracted it and run `ant create_repos` (which is a target that depends on `-create-razor-repository`) without any problem.

The `UserSandbox` directory is part of the OpenGrok repository, added in 2009 and has not changed since it seems.

**Comment by vladak** [comment]
No response for almost one month, closing. Feel free to reopen if the issue persists with 1.1-rc*.
