### ISSUE TITLE
"Index database(s) not found." should not be `200 OK`

### ISSUE THREAD

**Issue by cnst** [OpenGrok/OpenGrok#17]
When the index database is temporarily gone, OpenGrok returns `"Index database(s) not found."` (https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/web/SearchHelper.java) with a `200 OK` HTTP status code.

This breaks down HTTP accelerators (and probably various web-crawlers, too), which cache error pages momentarily (seconds), but non-error pages for an extended period of time (minutes or hours), where such OpenGrok error pages will be cached extensively, instead of being expired promptly.  Plus web-crawlers might update its index, instead of ignoring the result, and trying back later.

With `"Index database(s) not found."`, a non-200 http status code should be returned instead, probably `503 Service Unavailable`.

**Comment by vladak** [comment]
Since #1132 it is no longer easy to trigger this problem since index references are now cached so moving index directory away will not break the search because the file remains open. To reproduce this, one has to go and move the index directory away and then redeploy. Bunch of null pointer exceptions happen then :-)

Also, the error code should be set in `error.jsp`.
