### ISSUE TITLE
Improve line selection

### ISSUE THREAD

**Issue by sk-** [OpenGrok/OpenGrok#791]
Both github and codesearch (https://code.google.com/p/chromium/codesearch) have a much better line selection features.

They both support selecting multiple lines. Which is really useful.
And also they don't scroll the container in case the line is visible (actually codesearch does in some cases).

This issue should be probably split in two. 
ps:  I already started working on this. But I need to send some other pull request first.

**Comment by naseer** [comment]
Also, selecting lines should just select the code rather than line numbers. I know that the Line# at the top can toggle it, but it would be nicer if it just selected it correctly.

**Comment by tulinkry** [comment]
Multiple lines selection is already in the trunk with #1017

**Comment by vladak** [comment]
@naseer actually, selecting with line numbers is good for code reference where you can copy-n-paste the code including line numbers and then can say something like: "the issue happens on line X because the variable is initialized like so on line Y". It's one of the features I depend on, especially after @tulinkry fixed it with the spaces plugin.

The issue originally described in this issue is fixed as noted, so closing.
