### ISSUE TITLE
generate history index for renamed files in git repo separately

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#794]
Just like it was done for Mercurial in #22 (and bunch of follow-up changesets) it should possible to follow complete history of renamed files in git (and provide diffs between revisions of a file across renames).

**Comment by caminada** [comment]
I have a partial fix for this issue (the easy part...)

It's not yet implemented in the Indexer, aka creating of historycache at indexing time is not yet working (workaround: use option -k "*" to prevent cache building at all)

The second part has to be implemented in GitHistoryParser, but it's not as easy as in MercurialHistoryParser because git does not track renamed file with a tag like "file_copies:"
It will probably be very time consuming to iterate trough the full history of *all* files to recognize path changes for cache building...

**Comment by tulinkry** [comment]
Implemented in #1345

**Comment by caminada** [comment]
yeah! thank you @tulinkry 🥇
