### ISSUE TITLE
History cache db fails to initialise

### ISSUE THREAD

**Issue by tjbcea** [OpenGrok/OpenGrok#815]
Just installed Opengrok 0.12 on a new machine.
I have previously used 0.11 on a different machine, using a derby server for the history cache.

With 0.12, the history cache consistently fails to initialise, because the table OPENGROK.DIRECTORIES has a field PARENT which is used as part of a unique constraint. there is no 'NOT NULL' specifier for PARENT, and my derby engine refuses to use it for the constraint
I am using the most recent derby I could get, 10.10.1.1

**Comment by naseer** [comment]
Any idea if this is resolved in Derby 10.11 ? I updated recently and derby just hangs with high CPU usage.

**Comment by tulinkry** [comment]
JDBC is unsupported in 1.0

**Comment by vladak** [comment]
closing as OpenGrok dropped JDBC support for history index.

**Comment by sainath199** [comment]
so,the conclusion is As historycache is not created, we cannot enable History and Annotate links 
we can't use history

**Comment by vladak** [comment]
Well, yes. The indexer in the docker image runs with -H which means to
generate history cache for all projects. If the history cache is not
generated during indexing phase it cannot be displayed in the webapp since
the default behavior w.r.t. remote repositories is used which means the
history will not be generated on demand. Anyhow, there is either a problem
with your Clearcase setup (which you did not describe) or a bug. This
cannot be resolved until you do some analysis on your end or provide enough
detail of the setup so that someone that has Clearcase setup working can
provide some hints.

čt 27. 12. 2018 7:17 odesílatel sainath199 <notifications@github.com>
napsal:
