### ISSUE TITLE
java.io.FileNotFoundException while searching 

### ISSUE THREAD

**Issue by DmitryUlyanov** [OpenGrok/OpenGrok#874]
Hello, I successfully installed opengrok, the codebase was indexed with some git warnings (seems to have nothing in common with the issue, because I tried to index git-less base, and had the same problem).

So every time I search something I get this kind of error    
![screenshot from 2015-01-03 12 19 06](https://cloud.githubusercontent.com/assets/6727524/5602040/e1286282-9342-11e4-8d42-b78a30ff8f94.png)
These files exist, I tried to chmod them. 

According to some tutorials I tried to add 

```
grant codeBase "file:${catalina.base}/webapps/opengrok/" {
     permission java.security.AllPermission;};

grant codeBase "file:${catalina.base}/webapps/opengrok/WEB-INF/lib/"; {    permission java.security.AllPermission; };
```
into /etc/tomcat7/policy.d/50local.policy

I tried to run openGrok as sudo, but no change. Any Ideas ? Thanks!

**Comment by vladak** [comment]
The problem is that Tomcat is not running with enough privileges to access the file on disk. You need to make sure that your mirroring script creates the files so that Tomcat can access them.

Start with checking what user runs the Tomcat process as and what is the ownership and permissions of the file on disk. You can test by switching to the Tomcat user (`"su - tomcat"`, that is assuming `tomcat` is the user Tomcat server runs as) and accessing the file.

**Comment by tarzanek** [comment]
Can you also check
https://github.com/OpenGrok/OpenGrok/wiki/How-to-install-OpenGrok#Optional_setup_of_security_manager_for_tomcat

ev. verify if the howto isn't outdated, pls?
tia
L

**Comment by DmitryUlyanov** [comment]
Thank you for the responce. Tomcat service was owned by user `tomcat7`, who probably had no permissions to read and write into the filesystem. I don't think I'm going to open access to tomcat server to anyone and use it for something else but openGrok, so I made it easy: I edited file `/etc/default/tomcat7` changed `TOMCAT7_USER` and `TOMCAT7_GROUP` from `tomcat7` to myself.

Thanks!
