### ISSUE TITLE
support multiple git branch in layout

### ISSUE THREAD

**Issue by doris2012** [OpenGrok/OpenGrok#923]
this tool can't show multiple git branch

**Comment by vladak** [comment]
could you be more specific in what exactly do you want to see ?

**Comment by vladak** [comment]
closing due to lack of data, feel free to reopen.

**Comment by shankar-ananth** [comment]
I have run into the same problem. Here the challenge:

If we have a repo with multiple branches, the only way to make those branches indexable and searchable is by creating a physical directory for each branch (manually), and then running the indexer on each of those directories (which contain full copies of the same repo for each branch of interest). 

This seems to waste a lot of disk space, and is also not a great way of tracking multiple branches on the repository. If we could somehow have OpenGrok simply search for remote branches, switch to them and index them, then that would help tremendously.

**Comment by jimklimov** [comment]
I believe one improvement over "full copies" on general-purpose systems would be to have a (bare?) git repo with full history, and instances of workspaces for each branch checked out nearby that refer this full repo. So essentially you have the index checked out and synced over the network once, and the workspaces are done in local filesystem. On filesystems with compression and/or deduplication support, or maybe if git hardlink support helps out here, you might save even more resources.

By the way, does current OpenGrok support incremental indexing (so updated branches do not have to be rescanned for unchanged files and/or older commits), and can such indexes be cloned from a scan of e.g. master branch when we begin tracking a newly-found branch?

Also, do these checked-out workspaces have to stay in the filesystem after indexing, e.g. so that OpenGrok can display the sources in web-interface - or does it checkout and show straight from repo history using some SCM API?

**Comment by YoAm** [comment]
You can save the duplicate repositories using [git worktree](https://git-scm.com/docs/git-worktree). It creates a working tree in another directory, I use ../new_branch. This directory then contains a .git file containing the relative path to the repository. Unfortunately, OpenGrok doesn't parse this correctly and only the branch in the working tree containing the repository has functional history in OpenGrok.

**Comment by knolly** [comment]
The information is probably a bit late ;-) but I also had the same problem today and was able to solve it simply as follows:
As YoAm wrote: in the branch dir is not the .git dir but a file with the link to the branch git information with the name .git. If you delete or rename the .git file and create a symbolic link 
mac/linux: ln -s xx .git (xx = folderpath which is in the .git textfile) you will get the result, that you can click in the source files.
