### ISSUE TITLE
index time too long

### ISSUE THREAD

**Issue by charlesdbs** [OpenGrok/OpenGrok#955]
I have 1.4T codes,  when I execute index command, some ctags process cost too much time. One time It's running two weeks when I kill the process. I need help to reducing the execution time。

**Comment by tarzanek** [comment]
Can you check per logs which files are indexed?
Most probably your 1.4T code contains binaries that confuse ctags and "break" indexing ... 
I will need to work out the ctag limiter code to not give ctags binaries bigger than certain limit ... (I think the bug is #852 )

**Comment by tarzanek** [comment]
See ignore options for a workaround until this limit code will be in place ...

**Comment by tarzanek** [comment]
( #852 has the info on ignore options)

**Comment by charlesdbs** [comment]
from  debug logs

10:20:25 INFO: Add: .............../UserTag4LimitRule.java (JavaAnalyzer)
10:20:36 INFO: Add: .............../UserTagLimitRule.java (JavaAnalyzer)
10:20:47 INFO: Add:--------------/VerticalMarketLimitRule.java (JavaAnalyzer)
dir: /disk11/code/src/svn-develop/............./item/domain/misc
cur_count: 458058

Opengrok shell Xmx Set 81920M 
at zhe bigening handle 5 or 6 files/second.  when this commands running one days later .  maybe handle   10 files/minute.

**Comment by tarzanek** [comment]
Hmm, this time is definitely too long - where is it spent?
I doubt this is ctags, or if, make sure you use the latest, ev. switch to universal-ctags (project on github which forked old ctags, since they are kinda "dead")

BUT, my hypothesis is that your indexer spends time rather in checking the history for the file (svn might take a long time), or your systems disk/I/O/memory is a culprit ...

Can you check all of my hypothesis and verify they are not the prob?
E.g. disabling history might be a first step to see if it's not a problem (for git it shouldn't be a prob, for svn it MIGHT be a prob)

**Comment by charlesdbs** [comment]
thanks for helping, skip the history is faster than before. The remaining question is one cpu usage 100%，but others Idle, maybe its the question of ctags。

**Comment by tarzanek** [comment]
try truss/strace
jstacks
to see what is going on

**Comment by vladak** [comment]
No response for more than a year, closing. Feel free to reopen.
