### ISSUE TITLE
Variables defined in OPENGROK_CONFIGURATION are ignored

### ISSUE THREAD

**Issue by caipre** [OpenGrok/OpenGrok#965]
It seems to me that the variables specified in a configuration file will be ignored. The `LoadInstanceConfiguration()` function calls `DefaultInstanceConfiguration()` after sourcing the `OPENGROK_CONFIGURATION` file, effectively resetting variables to their default values (eg, `SRC_ROOT`).

It seems there are two old bugzilla tickets related to this: https://github.com/OpenGrok/OpenGrok/issues/268 https://github.com/OpenGrok/OpenGrok/issues/259

One could resolve this by using `bash` default-value assignment in `DefaultInstanceConfiguration()`:

```bash
SRC_ROOT:="${OPENGROK_INSTANCE_BASE}/src"
```

I'm not sure how portable the syntax is.

**Comment by tarzanek** [comment]
syntax should be posix, sh is used, so it should be generally portable to all *nix systems
if it's not, we need to improve it(send patches, also note that there is a "lint" for sh/bash/ksh which might give hints)

I don't personally use sourcing, perhaps @vladak does, I was hoping above would work, since people do call OpenGrok from cron tabs with sourcing of config, so if it doesn't work, we need to fix it ... 

regarding testing - Solaris 11 should have a posix sh , so test there, not sure about other OSes how much are they posix compliant ...

**Comment by vladak** [comment]
I think this approach is probably intentional. Sourcing the custom config file can set bunch of variables, out of which we would like to honor only those documented at the beginning of the `OpenGrok` script, e.g. those starting with `OPENGROK_` prefix or `JAVA_HOME` and the like. By sourcing a user supplied config file after setting the default variables could result in some of the internal variables of the script to be overridden and could cause the script to malfunction.
