### ISSUE TITLE
Multithread git log on individual files

### ISSUE THREAD

**Issue by bond-** [OpenGrok/OpenGrok#987]
OpenGrok is trying to fetch log for each and every file and I have files in the order of 1000's. If this can be made multithreaded(if not already), this slow step may become faster.

```
2015-08-31 17:19:04.404+0530 FINE t1133 Executor.exec: Executing command [/usr/bin/git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller, /path/to/project/file.xml] in directory /path/to/project
```

**Comment by vladak** [comment]
The reality is more complicated. The indexer fetches history for the whole repo first and stores it in a changeset->files hash which is then inverted into file->changesets hash and stored in the history cache. For files which have been renamed in the past, the history has to be fetched separately since there is no way how it can be deduced from the big hash. This step is executed in parallel so there is nothing to further parallelize.
